import { Form, FormSubmission, Integration, Domain, UserProfile, NotificationItem } from '../types';

export const initialUserProfile: UserProfile = {
  id: 'usr_101',
  name: 'Alex Rivera',
  email: 'alex.rivera@formflow.io',
  role: 'Operations Director',
  avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&q=80&w=200',
  organizationName: 'Acme Growth Labs',
  plan: 'Growth Plan',
};

export const initialForms: Form[] = [
  {
    id: 'form_contact_01',
    name: 'Contact Form',
    slug: 'contact-us',
    description: 'Standard website inbound contact and general inquiry form.',
    status: 'published',
    publishedVersion: 1,
    fieldsCount: 5,
    submissionsCount: 428,
    viewsCount: 1850,
    conversionRate: 23.1,
    createdAt: '2026-05-10T09:00:00Z',
    updatedAt: '2026-08-10T14:22:00Z',
    domain: 'forms.company.com',
  },
  {
    id: 'form_lead_02',
    name: 'Lead Generation Form',
    slug: 'get-started-lead-gen',
    description: 'Multi-step qualifier form capturing company size, role, and immediate project budget.',
    status: 'published',
    publishedVersion: 1,
    fieldsCount: 8,
    submissionsCount: 1240,
    viewsCount: 3820,
    conversionRate: 32.4,
    createdAt: '2026-06-01T11:30:00Z',
    updatedAt: '2026-08-11T10:15:00Z',
    domain: 'forms.company.com',
  },
  {
    id: 'form_service_03',
    name: 'Service Request Form',
    slug: 'request-service',
    description: 'Support ticket and technical service escalation request collector.',
    status: 'published',
    publishedVersion: 1,
    fieldsCount: 6,
    submissionsCount: 312,
    viewsCount: 1420,
    conversionRate: 21.9,
    createdAt: '2026-06-15T08:00:00Z',
    updatedAt: '2026-08-09T18:45:00Z',
    domain: 'app.leadsflow.io',
  },
  {
    id: 'form_demo_04',
    name: 'Demo Request Form',
    slug: 'book-a-demo',
    description: 'High-intent product walkthrough and sales meeting scheduling intake.',
    status: 'published',
    publishedVersion: 1,
    fieldsCount: 7,
    submissionsCount: 890,
    viewsCount: 2100,
    conversionRate: 42.3,
    createdAt: '2026-07-02T13:10:00Z',
    updatedAt: '2026-08-11T16:05:00Z',
    domain: 'forms.company.com',
  },
  {
    id: 'form_survey_05',
    name: 'Customer Feedback Survey',
    slug: 'q3-satisfaction-survey',
    description: 'NPS and qualitative feedback collection form for post-onboarding users.',
    status: 'draft',
    publishedVersion: undefined,
    fieldsCount: 10,
    submissionsCount: 0,
    viewsCount: 45,
    conversionRate: 0.0,
    createdAt: '2026-08-05T15:00:00Z',
    updatedAt: '2026-08-11T11:00:00Z',
  },
  {
    id: 'form_partner_06',
    name: 'Partner Onboarding Portal',
    slug: 'agency-partner-signup',
    description: 'Affiliate and reseller channel partner application intake.',
    status: 'archived',
    publishedVersion: 1,
    fieldsCount: 12,
    submissionsCount: 145,
    viewsCount: 980,
    conversionRate: 14.7,
    createdAt: '2026-03-12T10:00:00Z',
    updatedAt: '2026-07-20T12:30:00Z',
  },
];

export const initialSubmissions: FormSubmission[] = [
  {
    id: 'sub_901',
    formId: 'form_demo_04',
    formVersionId: 1,
    formName: 'Demo Request Form',
    submittedAt: '2026-08-11T22:15:00Z',
    status: 'new',
    userEmail: 'sarah.j@enterprise-tech.io',
    userName: 'Sarah Jenkins',
    userPhone: '+1 (555) 492-1092',
    userLocation: 'San Francisco, CA, USA',
    ipAddress: '192.168.1.104',
    fields: {
      'Full Name': 'Sarah Jenkins',
      'Work Email': 'sarah.j@enterprise-tech.io',
      'Company Name': 'EnterpriseTech Solutions',
      'Company Size': '250-500 employees',
      'Primary Interest': 'CRM Automation & Lead Routing',
      'Estimated Budget': '$25,000 / yr',
      Comments: 'Looking for an internal form automation engine that syncs directly with Webhooks and HubSpot.',
    },
    data: {
      'Full Name': 'Sarah Jenkins',
      'Work Email': 'sarah.j@enterprise-tech.io',
      'Company Name': 'EnterpriseTech Solutions',
      'Company Size': '250-500 employees',
      'Primary Interest': 'CRM Automation & Lead Routing',
      'Estimated Budget': '$25,000 / yr',
      Comments: 'Looking for an internal form automation engine that syncs directly with Webhooks and HubSpot.',
    },
    metadata: {
      referrer: 'https://google.com/search?q=formflow+demo',
      sourceUrl: 'https://forms.company.com/book-a-demo?utm_source=google&utm_medium=cpc&utm_campaign=enterprise_launch',
      utmParameters: {
        utm_source: 'google',
        utm_medium: 'cpc',
        utm_campaign: 'enterprise_launch',
        utm_term: 'form automation engine',
      },
      visitorId: 'vis_901_sf',
      sessionId: 'sess_901_sf',
      formId: 'form_demo_04',
      formVersion: 1,
      submissionId: 'sub_901',
    },
    actionExecutionStatus: [
      {
        actionId: 'act_wh_01',
        actionName: 'Webhooks Inbound Ingest',
        actionType: 'webhook',
        status: 'Success',
        executedAt: '2026-08-11T22:15:02Z',
        durationMs: 142,
        httpStatus: 200,
        responseBody: '{\n  "received": true,\n  "status": "ok",\n  "event": "submission_created",\n  "recordId": "rec_98213"\n}',
        details: 'HTTP POST payload delivered to https://api.acmegrowth.com/v1/webhooks/forms',
        retryCount: 0,
      },
      {
        actionId: 'act_n8n_01',
        actionName: 'n8n Enterprise Qualifier Workflow',
        actionType: 'n8n',
        status: 'Success',
        executedAt: '2026-08-11T22:15:03Z',
        durationMs: 280,
        httpStatus: 200,
        responseBody: '{\n  "workflowId": "wf_qualify_lead",\n  "executionId": "exec_88102",\n  "status": "finished"\n}',
        details: 'Dispatched to n8n webhook URL https://n8n.company.com/webhook/formflow-inbound',
        retryCount: 0,
      },
      {
        actionId: 'act_email_01',
        actionName: 'Sales Alert Notification',
        actionType: 'email',
        status: 'Success',
        executedAt: '2026-08-11T22:15:01Z',
        durationMs: 65,
        httpStatus: 200,
        responseBody: 'Email delivered via SMTP Gateway',
        details: 'Email alert dispatched to sales-team@acmegrowth.com',
        retryCount: 0,
      },
    ],
  },
  {
    id: 'sub_902',
    formId: 'form_lead_02',
    formVersionId: 1,
    formName: 'Lead Generation Form',
    submittedAt: '2026-08-11T20:40:00Z',
    status: 'new',
    userEmail: 'm.chen@apexglobal.com',
    userName: 'Michael Chen',
    userPhone: '+1 (555) 382-9102',
    userLocation: 'New York, NY, USA',
    ipAddress: '172.56.21.9',
    fields: {
      'Full Name': 'Michael Chen',
      'Work Email': 'm.chen@apexglobal.com',
      'Phone Number': '+1 (555) 382-9102',
      Industry: 'Financial Services',
      'Need Solution By': 'Q4 2026',
    },
    data: {
      'Full Name': 'Michael Chen',
      'Work Email': 'm.chen@apexglobal.com',
      'Phone Number': '+1 (555) 382-9102',
      Industry: 'Financial Services',
      'Need Solution By': 'Q4 2026',
    },
    metadata: {
      referrer: 'https://linkedin.com/feed',
      sourceUrl: 'https://forms.company.com/get-started-lead-gen?utm_source=linkedin&utm_medium=social',
      utmParameters: {
        utm_source: 'linkedin',
        utm_medium: 'social',
        utm_campaign: 'q3_leadgen',
      },
      visitorId: 'vis_902_ny',
      sessionId: 'sess_902_ny',
      formId: 'form_lead_02',
      formVersion: 1,
      submissionId: 'sub_902',
    },
    actionExecutionStatus: [
      {
        actionId: 'act_ghl_01',
        actionName: 'GoHighLevel Contact Sync',
        actionType: 'ghl',
        status: 'Failed',
        executedAt: '2026-08-11T20:40:05Z',
        durationMs: 1250,
        httpStatus: 502,
        responseBody: '{\n  "error": "Bad Gateway",\n  "message": "GHL sub-account API endpoint timeout after 1000ms"\n}',
        details: 'GHL API request failed due to server timeout. Action marked for retry.',
        retryCount: 2,
      },
      {
        actionId: 'act_wh_02',
        actionName: 'Webhooks Ingest Endpoint',
        actionType: 'webhook',
        status: 'Success',
        executedAt: '2026-08-11T20:40:02Z',
        durationMs: 95,
        httpStatus: 200,
        responseBody: '{\n  "status": "ok"\n}',
        details: 'Payload delivered to https://api.acmegrowth.com/v1/webhooks/forms',
        retryCount: 0,
      },
    ],
  },
  {
    id: 'sub_903',
    formId: 'form_service_03',
    formVersionId: 1,
    formName: 'Service Request Form',
    submittedAt: '2026-08-11T18:10:00Z',
    status: 'reviewed',
    userEmail: 'david.k@cloudworks.org',
    userName: 'David Vance',
    userPhone: '+1 (555) 812-3019',
    userLocation: 'Austin, TX, USA',
    ipAddress: '68.12.90.11',
    fields: {
      'Full Name': 'David Vance',
      Email: 'david.k@cloudworks.org',
      'Issue Category': 'Domain CNAME DNS Configuration',
      Priority: 'High',
      Description: 'Need help pointing custom sub-domain forms.cloudworks.org to FormFlow ingress servers.',
    },
    data: {
      'Full Name': 'David Vance',
      Email: 'david.k@cloudworks.org',
      'Issue Category': 'Domain CNAME DNS Configuration',
      Priority: 'High',
      Description: 'Need help pointing custom sub-domain forms.cloudworks.org to FormFlow ingress servers.',
    },
    metadata: {
      referrer: 'https://app.leadsflow.io/help',
      sourceUrl: 'https://app.leadsflow.io/request-service',
      utmParameters: {},
      visitorId: 'vis_903_tx',
      sessionId: 'sess_903_tx',
      formId: 'form_service_03',
      formVersion: 1,
      submissionId: 'sub_903',
    },
  },
  {
    id: 'sub_904',
    formId: 'form_contact_01',
    formVersionId: 1,
    formName: 'Contact Form',
    submittedAt: '2026-08-11T14:25:00Z',
    status: 'processed',
    userEmail: 'elena.rodriguez@designify.co',
    userName: 'Elena Rodriguez',
    userPhone: '+1 (555) 902-1144',
    userLocation: 'Chicago, IL, USA',
    ipAddress: '99.44.12.87',
    fields: {
      'Full Name': 'Elena Rodriguez',
      Email: 'elena.rodriguez@designify.co',
      Subject: 'Custom CSS and Webhook Integration Query',
      Message: 'Does FormFlow support custom font loading and direct Zapier trigger hooks on form submission?',
    },
    data: {
      'Full Name': 'Elena Rodriguez',
      Email: 'elena.rodriguez@designify.co',
      Subject: 'Custom CSS and Webhook Integration Query',
      Message: 'Does FormFlow support custom font loading and direct Zapier trigger hooks on form submission?',
    },
    metadata: {
      referrer: 'Direct Visit',
      sourceUrl: 'https://forms.company.com/contact-us',
      utmParameters: {},
      visitorId: 'vis_904_il',
      sessionId: 'sess_904_il',
      formId: 'form_contact_01',
      formVersion: 1,
      submissionId: 'sub_904',
    },
  },
  {
    id: 'sub_905',
    formId: 'form_demo_04',
    formVersionId: 1,
    formName: 'Demo Request Form',
    submittedAt: '2026-08-10T19:50:00Z',
    status: 'processed',
    userEmail: 't.bradley@vanguard-ops.com',
    userName: 'Tom Bradley',
    userPhone: '+44 20 7946 0912',
    userLocation: 'London, UK',
    ipAddress: '82.165.19.4',
    fields: {
      'Full Name': 'Tom Bradley',
      'Work Email': 't.bradley@vanguard-ops.com',
      'Company Name': 'Vanguard Ops UK',
      'Company Size': '500+ employees',
      'Primary Interest': 'Multi-domain Form Hosting & White-labeling',
    },
    data: {
      'Full Name': 'Tom Bradley',
      'Work Email': 't.bradley@vanguard-ops.com',
      'Company Name': 'Vanguard Ops UK',
      'Company Size': '500+ employees',
      'Primary Interest': 'Multi-domain Form Hosting & White-labeling',
    },
    metadata: {
      referrer: 'https://techcrunch.com/articles/formflow-funding',
      sourceUrl: 'https://forms.company.com/book-a-demo',
      utmParameters: {
        utm_source: 'techcrunch',
        utm_medium: 'referral',
      },
      visitorId: 'vis_905_uk',
      sessionId: 'sess_905_uk',
      formId: 'form_demo_04',
      formVersion: 1,
      submissionId: 'sub_905',
    },
  },
];

export const initialIntegrations: Integration[] = [
  {
    id: 'int_n8n',
    name: 'n8n Workflow Automation',
    description: 'Trigger node-based automated workflows with raw or mapped JSON payloads.',
    category: 'Automation',
    iconName: 'Workflow',
    status: 'connected',
    lastSync: '2026-08-11T20:00:00Z',
    connectedFormsCount: 3,
    webhookUrl: 'https://n8n.company.com/webhook/formflow-inbound',
    apiKeySet: true,
  },
  {
    id: 'int_ghl',
    name: 'GoHighLevel (GHL)',
    description: 'Create and update contacts, custom fields, and tags in GoHighLevel sub-accounts.',
    category: 'CRM',
    iconName: 'Users',
    status: 'connected',
    lastSync: '2026-08-11T21:30:00Z',
    connectedFormsCount: 2,
    apiKeySet: true,
  },
  {
    id: 'int_zapier',
    name: 'Zapier',
    description: 'Trigger 5,000+ app workflows automatically when a form is submitted.',
    category: 'Automation',
    iconName: 'Zap',
    status: 'connected',
    lastSync: '2026-08-11T22:30:00Z',
    connectedFormsCount: 4,
    apiKeySet: true,
  },
  {
    id: 'int_webhook',
    name: 'HTTP Webhooks',
    description: 'Send instant JSON payloads to your custom backend or API server.',
    category: 'Automation',
    iconName: 'Webhook',
    status: 'connected',
    lastSync: '2026-08-11T22:15:00Z',
    connectedFormsCount: 3,
    webhookUrl: 'https://api.acmegrowth.com/v1/webhooks/forms',
  },
  {
    id: 'int_sheets',
    name: 'Google Sheets',
    description: 'Append form responses in real-time to a live spreadsheet.',
    category: 'Spreadsheets',
    iconName: 'FileSpreadsheet',
    status: 'connected',
    lastSync: '2026-08-11T20:40:00Z',
    connectedFormsCount: 2,
    apiKeySet: true,
  },
  {
    id: 'int_hubspot',
    name: 'HubSpot CRM',
    description: 'Create or update contacts and deals automatically from inbound leads.',
    category: 'CRM',
    iconName: 'Users',
    status: 'connected',
    lastSync: '2026-08-11T16:05:00Z',
    connectedFormsCount: 2,
    apiKeySet: true,
  },
  {
    id: 'int_slack',
    name: 'Slack Notifications',
    description: 'Broadcast form submission summaries to designated Slack channels.',
    category: 'Notifications',
    iconName: 'MessageSquare',
    status: 'disconnected',
    connectedFormsCount: 0,
  },
  {
    id: 'int_salesforce',
    name: 'Salesforce',
    description: 'Direct enterprise lead ingestion and task assignment.',
    category: 'CRM',
    iconName: 'Database',
    status: 'disconnected',
    connectedFormsCount: 0,
  },
  {
    id: 'int_stripe',
    name: 'Stripe Payments',
    description: 'Collect payments and subscriptions directly inside form flows.',
    category: 'Payments',
    iconName: 'CreditCard',
    status: 'disconnected',
    connectedFormsCount: 0,
  },
  {
    id: 'int_mailchimp',
    name: 'Mailchimp',
    description: 'Subscribe lead emails into audiences and drip marketing campaigns.',
    category: 'Email',
    iconName: 'Mail',
    status: 'disconnected',
    connectedFormsCount: 0,
  },
];

export const initialDomains: Domain[] = [
  {
    id: 'dom_01',
    domainName: 'forms.company.com',
    status: 'active',
    connectedFormsCount: 3,
    sslEnabled: true,
    createdAt: '2026-05-01T10:00:00Z',
    isDefault: true,
    cnameRecord: 'ingress.formflow.io',
  },
  {
    id: 'dom_02',
    domainName: 'app.leadsflow.io',
    status: 'active',
    connectedFormsCount: 1,
    sslEnabled: true,
    createdAt: '2026-06-10T14:00:00Z',
    isDefault: false,
    cnameRecord: 'ingress.formflow.io',
  },
  {
    id: 'dom_03',
    domainName: 'intake.growthlab.org',
    status: 'pending_dns',
    connectedFormsCount: 0,
    sslEnabled: false,
    createdAt: '2026-08-08T09:30:00Z',
    isDefault: false,
    cnameRecord: 'ingress.formflow.io',
  },
];

export const initialNotifications: NotificationItem[] = [
  {
    id: 'notif_101',
    title: 'New High-Intent Lead',
    message: 'Sarah Jenkins submitted Demo Request Form ($25k budget).',
    timestamp: '2026-08-11T22:15:00Z',
    read: false,
    type: 'submission',
  },
  {
    id: 'notif_102',
    title: 'Webhook Sync Success',
    message: 'HTTP Webhooks successfully synced 15 new lead payloads.',
    timestamp: '2026-08-11T21:00:00Z',
    read: false,
    type: 'integration',
  },
  {
    id: 'notif_103',
    title: 'SSL Certificate Issued',
    message: 'SSL configuration completed for app.leadsflow.io',
    timestamp: '2026-08-10T12:00:00Z',
    read: true,
    type: 'domain',
  },
];
